//! Host-run integration tests for the dlmm-reader plugin's pure core.
//! No wasm toolchain required — `cargo test` from this directory is enough.
//!
//! Exercises the args parsing + shaping path with the same ground-truth
//! fixtures dlmm-core uses (tests/fixtures.json, generated by
//! tools/gen-fixtures.cjs from the official SDK).

use base64::Engine;
use dlmm_core::decoder::{decode_bin_array, decode_lb_pair, decode_position};
use dlmm_reader::shape::{shape_report, shape_status, Args};

fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!("../../dlmm-core/tests/fixtures.json")).unwrap()
}

fn b64(v: &serde_json::Value) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(v.as_str().unwrap())
        .unwrap()
}

#[test]
fn args_parse_with_config_injection() {
    let args: Args = serde_json::from_str(
        r#"{
            "mode": "report",
            "position_ids": ["7fTxDfcWTMVJg2r26Jv496HsuEBi6Hc77QEsHE9NSVZ1"],
            "__config": {
                "rpc_url": "https://api.mainnet-beta.solana.com",
                "owner_pubkey": "2KDS5vtFQJyYJApNGoPVaBSaYP7Vp4R3txRM9SYj13BW"
            }
        }"#,
    )
    .unwrap();
    assert_eq!(args.mode, "report");
    assert_eq!(args.position_ids.len(), 1);
    let cfg = args.config.expect("__config injected");
    assert_eq!(cfg.rpc_url, "https://api.mainnet-beta.solana.com");
    assert_eq!(
        cfg.owner_pubkey.as_deref(),
        Some("2KDS5vtFQJyYJApNGoPVaBSaYP7Vp4R3txRM9SYj13BW")
    );
}

#[test]
fn args_without_config_are_flagged() {
    let args: Args = serde_json::from_str(r#"{"mode": "status"}"#).unwrap();
    assert!(args.config.is_none());
    // the wasm shim rejects this: "missing __config (config_read permission?)"
}

#[test]
fn report_end_to_end_from_fixture() {
    let f = fixture();
    let pos = decode_position(&b64(&f["position_v2"])).expect("decode position");
    let lb = decode_lb_pair(&b64(&f["lb_pair"])).expect("decode lb_pair");

    let bin_arr = decode_bin_array(&b64(&f["bin_array_aligned"])).expect("decode bin array");
    let r = shape_report(
        "7fTxDfcWTMVJg2r26Jv496HsuEBi6Hc77QEsHE9NSVZ1",
        &pos,
        &lb,
        Some("2KDS5vtFQJyYJApNGoPVaBSaYP7Vp4R3txRM9SYj13BW"),
        Some(150.0),
        Some(1.0),
        9,
        6,
        &[bin_arr],
    );

    // range from position, active from lb_pair, in-range (8500 ∈ [8450, 8520])
    assert_eq!(r["range"], serde_json::json!([8450, 8520]));
    assert_eq!(r["active_bin_id"], 8500);
    assert_eq!(r["in_range"], true);
    assert_eq!(r["owner_match"], true);
    // claimable 1_000_000 raw x (9 dec) + 2_000_000 raw y (6 dec)
    // = 0.001 x * $150 + 2.0 y * $1 = $0.15 + $2.00 = $2.15
    let usd = r["claimable"]["usd_approx"].as_f64().unwrap();
    assert!((usd - 2.15).abs() < 1e-9, "usd_approx = {usd}");
}

#[test]
fn status_mode_settlement_chain() {
    // Before the pending tx lands: same hash → not settled.
    let before = shape_status(
        "nonce123",
        "6Y2jVHPNRp1dii1mBa9Mn4D4ttRDdSocEjFXAWSzbYxZ",
        Some("6Y2jVHPNRp1dii1mBa9Mn4D4ttRDdSocEjFXAWSzbYxZ"),
    );
    assert_eq!(before["settled"], false);

    // After it lands: hash advanced → settled, new proposal safe.
    let after = shape_status(
        "nonce123",
        "9xQq1Uwb1hP9z9uWnQv4kLmNvq1WvB5nXq2mR9tY3vZk",
        Some("6Y2jVHPNRp1dii1mBa9Mn4D4ttRDdSocEjFXAWSzbYxZ"),
    );
    assert_eq!(after["settled"], true);

    // No previous record → cannot determine (fail-closed).
    let unknown =
        shape_status("nonce123", "6Y2jVHPNRp1dii1mBa9Mn4D4ttRDdSocEjFXAWSzbYxZ", None);
    assert_eq!(unknown["settled"], false);
}
