//! Cross-checks against the ground-truth fixtures (tests/fixtures.json),
//! generated by tools/gen-fixtures.mjs:
//!
//!   * PDA vectors  — derived with the official SDK's findProgramAddressSync
//!   * tx_claim_b58 — serialized with web3.js Transaction.serialize (official
//!     legacy wire format), unsigned, durable-nonce
//!   * account bytes — PositionV2 / LbPair / BinArray laid out from the
//!     program IDL (bytemuck C-repr), sized 8120 / 888 / 10136
//!   * nonce_account — System-Program nonce layout (hash at offset 40)
//!
//! The instruction fixtures in the same JSON (claim_ix / remove_ix / add_ix)
//! are hand-encoded from the same IDL spec this crate implements — they pin
//! the Rust encoder against the spec, not against an independent source.

use base64::Engine;
use dlmm_core::decoder::{
    claimable_fees, claimable_fees_with_bins, decode_bin_array, decode_lb_pair, decode_position,
    fee_recipient, position_amounts, total_liquidity_shares, BIN_ARRAY_LEN, LB_PAIR_LEN,
    POSITION_V2_LEN,
};
use dlmm_core::nonce::{decode_nonce_hash, is_settled, nonce_hash_base58};
use dlmm_core::pda;
use dlmm_core::tx::{
    associated_token_address, bin_array_metas, bin_id_to_bin_array_index, build_claim_instructions,
    encode_unsigned_tx, PoolCtx, TOKEN_PROGRAM_ID,
};
use dlmm_core::validate::{
    validate_active_bin_slippage, validate_bin_array_range, validate_claimable, validate_owned,
    validate_range, ValidationError, MAX_ACTIVE_BIN_SLIPPAGE,
};
use serde_json::Value;
use solana_pubkey::Pubkey;

fn fixtures() -> Value {
    serde_json::from_str(include_str!("fixtures.json")).expect("fixtures.json parses")
}

fn pk(v: &Value) -> Pubkey {
    v.as_str().unwrap().parse().unwrap()
}

fn b64(v: &Value) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(v.as_str().unwrap())
        .unwrap()
}

fn b58(s: &str) -> Vec<u8> {
    bs58::decode(s).into_vec().unwrap()
}

// ---------------------------------------------------------------------------
// PDA cross-check (SDK findProgramAddressSync ground truth)
// ---------------------------------------------------------------------------

#[test]
fn pdas_match_sdk_derivation() {
    let f = fixtures();
    let pool = pk(&f["keys"]["pool"]);
    let program = pk(&f["keys"]["program"]);

    assert_eq!(
        pda::bin_array(&pool, 120, &program).0.to_string(),
        f["pdas"]["bin_array_120"]
    );
    assert_eq!(
        pda::bin_array(&pool, 121, &program).0.to_string(),
        f["pdas"]["bin_array_121"]
    );
    assert_eq!(
        pda::bin_array(&pool, -1, &program).0.to_string(),
        f["pdas"]["bin_array_neg1"]
    );
    assert_eq!(
        pda::event_authority(&program).0.to_string(),
        f["pdas"]["event_authority"]
    );
    assert_eq!(
        pda::bin_array_bitmap_extension(&pool, &program)
            .0
            .to_string(),
        f["pdas"]["bitmap_extension"]
    );
}

// ---------------------------------------------------------------------------
// Account decoding (IDL bytemuck layout ground truth)
// ---------------------------------------------------------------------------

#[test]
fn decodes_position_v2_from_fixture() {
    let f = fixtures();
    let pos = decode_position(&b64(&f["position_v2"])).expect("decode");

    assert_eq!(pos.lb_pair.to_string(), f["keys"]["pool"]);
    assert_eq!(pos.owner.to_string(), f["keys"]["owner"]);
    assert_eq!(pos.lower_bin_id, 8450);
    assert_eq!(pos.upper_bin_id, 8520);
    assert_eq!(pos.version, 2);

    // non-empty bins at index 0 and 5
    assert_eq!(pos.liquidity_shares[0], 1_000_000_000);
    assert_eq!(pos.liquidity_shares[5], 500_000_000);
    assert_eq!(pos.liquidity_shares[1], 0);
    assert_eq!(pos.fee_infos[0].fee_x_pending, 1_000_000);
    assert_eq!(pos.fee_infos[5].fee_y_pending, 2_000_000);

    let (fx, fy) = claimable_fees(&pos);
    assert_eq!((fx, fy), (1_000_000, 2_000_000));
    assert_eq!(total_liquidity_shares(&pos), 1_500_000_000);
    // fee_owner == owner in the fixture → recipient is owner
    assert_eq!(fee_recipient(&pos), pos.owner);
}

#[test]
fn decodes_lb_pair_from_fixture() {
    let f = fixtures();
    let lb = decode_lb_pair(&b64(&f["lb_pair"])).expect("decode");

    assert_eq!(lb.active_id, 8500);
    assert_eq!(lb.bin_step, 10);
    assert_eq!(lb.token_x_mint.to_string(), f["keys"]["token_x_mint"]);
    assert_eq!(lb.token_y_mint.to_string(), f["keys"]["token_y_mint"]);
    assert_eq!(lb.reserve_x.to_string(), f["keys"]["reserve_x"]);
    assert_eq!(lb.reserve_y.to_string(), f["keys"]["reserve_y"]);
}

#[test]
fn decodes_bin_array_from_fixture() {
    let f = fixtures();
    let ba = decode_bin_array(&b64(&f["bin_array"])).expect("decode");

    assert_eq!(ba.index, 120);
    assert_eq!(ba.lb_pair.to_string(), f["keys"]["pool"]);
    assert_eq!(ba.bins[0].amount_x, 2_000_000_000);
    assert_eq!(ba.bins[0].amount_y, 300_000_000);
    assert_eq!(ba.bins[0].liquidity_supply, 2_000_000_000);
    assert_eq!(ba.bins[1].liquidity_supply, 0);
    assert_eq!(ba.bins[69].amount_x, 0);
}

#[test]
fn position_amounts_matches_share_times_reserve_ratio() {
    let f = fixtures();
    let pos = decode_position(&b64(&f["position_v2"])).expect("decode position");
    // Aligned fixture: array 120 covers bins 8400..8469, so position bins
    // 8450 (share idx 0) and 8455 (share idx 5) live at inner offsets 50/55.
    let ba = decode_bin_array(&b64(&f["bin_array_aligned"])).expect("decode aligned bin array");

    let (x, y) = position_amounts(&pos, &[ba]);

    // share 1e9 in bin 8450: liquidity 2e9, amounts 2e9/3e8
    //   → x = 1e9 * 2e9 / 2e9 = 1_000_000_000, y = 1e9 * 3e8 / 2e9 = 150_000_000
    // share 5e8 in bin 8455: liquidity 1e9, amounts 1e9/1e8
    //   → x = 5e8 * 1e9 / 1e9 = 500_000_000,  y = 5e8 * 1e8 / 1e9 = 50_000_000
    assert_eq!((x, y), (1_500_000_000, 200_000_000));
}

#[test]
fn position_amounts_is_zero_without_bin_arrays() {
    let f = fixtures();
    let pos = decode_position(&b64(&f["position_v2"])).expect("decode position");
    assert_eq!(position_amounts(&pos, &[]), (0, 0));
}

// The per-bin per-token claimable math: the position's raw `fee_x_pending`
// undercounts fees accrued since the last claim. This pins the correct
// formula:
//   new_fee = (share >> SCALE_OFFSET) * (bin_fee_stored - fee_complete)
//            >> SCALE_OFFSET
//   claimable = new_fee + fee_pending
#[test]
fn claimable_fees_uses_per_bin_per_token_math() {
    let f = fixtures();
    let pos = decode_position(&b64(&f["position_v2"])).expect("decode position");
    let mut ba = decode_bin_array(&b64(&f["bin_array_aligned"])).expect("decode aligned bin array");

    // Position bin 8450 = inner offset 50 in array 120 (covers 8400..8469).
    // Position liquidity_shares[0] → that bin; the position's fee_infos[0].
    let bin_idx = 50usize;
    let share = pos.liquidity_shares[0];
    let fee_pending_x = pos.fee_infos[0].fee_x_pending;
    assert!(share > 0, "fixture position must hold liquidity at bin 8450");
    assert!(fee_pending_x > 0, "fixture position must have pending fees");

    // Give the bin a per-token stored fee above the position's last-claimed
    // value, so the per-token delta term is non-zero.
    let delta_per_token: u128 = 1 << 10; // in Q64.64 units
    ba.bins[bin_idx].fee_amount_x_per_token_stored =
        pos.fee_infos[0].fee_x_per_token_complete + delta_per_token;

    let (x, _y) = claimable_fees_with_bins(&pos, &[ba]);
    // expected = ((share >> 64) * delta_per_token) >> 64 + fee_pending_x
    let expected = (((share >> 64) as u128 * delta_per_token) >> 64) as u64 + fee_pending_x;
    assert_eq!(x, expected, "per-token delta term must be added to pending");
}

#[test]
fn rejects_wrong_discriminator_and_short_data() {
    let mut data = vec![0u8; POSITION_V2_LEN];
    data[..8].copy_from_slice(&[1, 2, 3, 4, 5, 6, 7, 8]);
    assert!(decode_position(&data).is_err());

    let mut ok = vec![0u8; POSITION_V2_LEN];
    ok[..8].copy_from_slice(&dlmm_core::decoder::POSITION_V2_DISCRIMINATOR);
    assert!(decode_position(&ok[..ok.len() - 1]).is_err());
    assert!(decode_position(&ok).is_ok());

    assert_eq!(LB_PAIR_LEN, 888);
    assert_eq!(BIN_ARRAY_LEN, 10136);
}

// ---------------------------------------------------------------------------
// Durable nonce (System Program layout ground truth)
// ---------------------------------------------------------------------------

#[test]
fn nonce_hash_extraction_matches_fixture() {
    let f = fixtures();
    let data = b64(&f["nonce_account"]);
    assert_eq!(data.len(), 80); // 4 + 4 + 32 + 32 + 8

    let hash = decode_nonce_hash(&data).expect("decode");
    assert_eq!(bs58::encode(hash).into_string(), f["keys"]["nonce_hash"]);
    assert_eq!(nonce_hash_base58(&data).unwrap(), f["keys"]["nonce_hash"]);

    // settlement evidence
    let mut changed = hash;
    changed[0] ^= 0x01;
    assert!(is_settled(&hash, &changed));
    assert!(!is_settled(&hash, &hash));
    assert!(decode_nonce_hash(&data[..39]).is_err());
}

// ---------------------------------------------------------------------------
// Instruction encoding (IDL spec ground truth — see module docs)
// ---------------------------------------------------------------------------

#[test]
fn ata_derivation_matches_web3js_ground_truth() {
    let f = fixtures();
    let owner = pk(&f["keys"]["owner"]);
    let token_program = TOKEN_PROGRAM_ID.parse().unwrap();
    let x = associated_token_address(&owner, &pk(&f["keys"]["token_x_mint"]), &token_program);
    let y = associated_token_address(&owner, &pk(&f["keys"]["token_y_mint"]), &token_program);
    assert_eq!(x.to_string(), f["keys"]["user_token_x"]);
    assert_eq!(y.to_string(), f["keys"]["user_token_y"]);
}

fn fixture_pool_ctx(f: &Value) -> PoolCtx {
    PoolCtx {
        lb_pair: pk(&f["keys"]["pool"]),
        reserve_x: pk(&f["keys"]["reserve_x"]),
        reserve_y: pk(&f["keys"]["reserve_y"]),
        token_x_mint: pk(&f["keys"]["token_x_mint"]),
        token_y_mint: pk(&f["keys"]["token_y_mint"]),
        token_program: TOKEN_PROGRAM_ID.parse().unwrap(),
    }
}

#[test]
fn claim_ix_matches_idl_layout() {
    let f = fixtures();
    let pool = fixture_pool_ctx(&f);
    let program = pk(&f["keys"]["program"]);
    let event_authority = pda::event_authority(&program).0;
    let bin_arrays: Vec<solana_pubkey::Pubkey> =
        bin_array_metas(&pool.lb_pair, 8450, 8520, &program)
            .into_iter()
            .map(|m| m.pubkey)
            .collect();

    let ix = dlmm_core::tx::claim_fee2_ix(
        &pool,
        pk(&f["keys"]["position"]),
        pk(&f["keys"]["owner"]),
        pk(&f["keys"]["user_token_x"]),
        pk(&f["keys"]["user_token_y"]),
        8450,
        8520,
        bin_arrays.clone(),
        dlmm_core::tx::MEMO_PROGRAM_ID.parse().unwrap(),
        event_authority,
        program,
    );

    let expected: Value = f["claim_ix"].clone();
    assert_eq!(ix.program_id.to_string(), expected["program_id"]);
    assert_eq!(ix.data, b64(&expected["data"]));
    let keys: Vec<(String, bool, bool)> = ix
        .accounts
        .iter()
        .map(|m| (m.pubkey.to_string(), m.is_signer, m.is_writable))
        .collect();
    let exp_keys: Vec<(String, bool, bool)> = expected["keys"]
        .as_array()
        .unwrap()
        .iter()
        .map(|k| {
            (
                k["pubkey"].as_str().unwrap().to_string(),
                k["isSigner"].as_bool().unwrap(),
                k["isWritable"].as_bool().unwrap(),
            )
        })
        .collect();
    assert_eq!(keys, exp_keys);
    assert_eq!(bin_arrays.len(), 2);
}

#[test]
fn bin_array_index_math_is_floor_div() {
    assert_eq!(bin_id_to_bin_array_index(8450), 120);
    assert_eq!(bin_id_to_bin_array_index(8520), 121);
    assert_eq!(bin_id_to_bin_array_index(0), 0);
    assert_eq!(bin_id_to_bin_array_index(69), 0);
    assert_eq!(bin_id_to_bin_array_index(70), 1);
    assert_eq!(bin_id_to_bin_array_index(-1), -1);
    assert_eq!(bin_id_to_bin_array_index(-70), -1);
    assert_eq!(bin_id_to_bin_array_index(-71), -2);
}

// ---------------------------------------------------------------------------
// Full transaction wire format (web3.js serialize ground truth)
// ---------------------------------------------------------------------------

#[test]
fn unsigned_claim_tx_matches_web3js_wire_format() {
    let f = fixtures();
    let pool = fixture_pool_ctx(&f);
    let program = pk(&f["keys"]["program"]);
    let nonce = pk(&f["keys"]["nonce"]);
    let owner = pk(&f["keys"]["owner"]);
    let position = pk(&f["keys"]["position"]);

    let blockhash: [u8; 32] = b58(f["keys"]["nonce_hash"].as_str().unwrap())
        .try_into()
        .unwrap();

    let ixs = build_claim_instructions(
        nonce,
        owner,
        &pool,
        position,
        pk(&f["keys"]["user_token_x"]),
        pk(&f["keys"]["user_token_y"]),
        8450,
        8520,
        program,
    );
    assert_eq!(ixs.len(), 2); // AdvanceNonceAccount first
    assert_eq!(
        ixs[0].program_id.to_string(),
        "11111111111111111111111111111111"
    );

    let bytes = encode_unsigned_tx(&ixs, &blockhash, &owner);
    let expected = b58(f["tx_claim_b58"].as_str().unwrap());
    assert_eq!(
        bytes, expected,
        "claim tx must match web3.js serialization byte-for-byte"
    );
}

#[test]
fn unsigned_rebalance_tx_matches_web3js_wire_format() {
    let f = fixtures();
    let pool = fixture_pool_ctx(&f);
    let program = pk(&f["keys"]["program"]);
    let nonce = pk(&f["keys"]["nonce"]);
    let owner = pk(&f["keys"]["owner"]);
    let position = pk(&f["keys"]["position"]);

    let blockhash: [u8; 32] = b58(f["keys"]["nonce_hash"].as_str().unwrap())
        .try_into()
        .unwrap();

    let ixs = dlmm_core::tx::build_rebalance_instructions(
        nonce,
        owner,
        &pool,
        position,
        pk(&f["keys"]["user_token_x"]),
        pk(&f["keys"]["user_token_y"]),
        8450,          // current_low
        8520,          // current_high
        8450,          // new_low
        8520,          // new_high
        8500,          // active_id
        1_500_000_000, // amount_x
        200_000_000,   // amount_y
        3,             // max_active_bin_slippage
        dlmm_core::tx::StrategyType::SpotImBalanced,
        [0u8; 64], // parameteres
        program,
    );
    assert_eq!(ixs.len(), 3); // AdvanceNonceAccount, remove, add

    let bytes = encode_unsigned_tx(&ixs, &blockhash, &owner);
    let expected = b58(f["tx_rebalance_b58"].as_str().unwrap());
    assert_eq!(
        bytes, expected,
        "rebalance tx must match web3.js serialization byte-for-byte"
    );
}

// ---------------------------------------------------------------------------
// Mechanical validation (fail-closed rules)
// ---------------------------------------------------------------------------

#[test]
fn validation_rules_fail_closed() {
    let f = fixtures();
    let pos = decode_position(&b64(&f["position_v2"])).unwrap();
    let owner = pk(&f["keys"]["owner"]);
    let stranger = Pubkey::new_unique();
    // Aligned bin array covers position bins 8450..8469 (array index 120).
    let bin_arr = decode_bin_array(&b64(&f["bin_array_aligned"])).unwrap();

    // ownership
    assert!(validate_owned(&pos, &owner).is_ok());
    assert_eq!(
        validate_owned(&pos, &stranger),
        Err(ValidationError::NotOwned)
    );

    // range
    assert!(validate_range(8400, 8600, 8500).is_ok());
    assert_eq!(
        validate_range(8600, 8400, 8500),
        Err(ValidationError::InvalidRange)
    );
    assert_eq!(
        validate_range(8400, 8499, 8500),
        Err(ValidationError::RangeDoesNotContainActiveBin)
    );

    // active-bin slippage
    assert!(validate_active_bin_slippage(8500, 8500).is_ok());
    assert!(validate_active_bin_slippage(8502, 8500).is_ok());
    assert_eq!(
        validate_active_bin_slippage(8505, 8500),
        Err(ValidationError::ActiveBinTooFar(5))
    );

    // claimable — the fixture has fees, so it passes
    assert!(validate_claimable(&pos, &[bin_arr.clone()]).is_ok());

    // bin-array range
    assert!(validate_bin_array_range(8450, 8520).is_ok());
    // 512 * 70 = 35840 → index 512 rejected
    assert!(validate_bin_array_range(-35770, 35839).is_ok());
    // -35771 → index -512 → rejected
    assert!(matches!(
        validate_bin_array_range(-35771, -35770),
        Err(ValidationError::BinArrayOverflow(_))
    ));
    assert!(matches!(
        validate_bin_array_range(35840, 35900),
        Err(ValidationError::BinArrayOverflow(_))
    ));
}

#[test]
fn empty_position_fails_claimable_check() {
    // zero liquidity, zero fees
    let f = fixtures();
    let mut bytes = b64(&f["position_v2"]);
    // zero out the liquidity shares (start of shares = 8 + 64)
    for b in bytes[8 + 64..8 + 64 + 70 * 16].iter_mut() {
        *b = 0;
    }
    let pos = decode_position(&bytes).unwrap();
    let bin_arr = decode_bin_array(&b64(&f["bin_array_aligned"])).unwrap();
    assert_eq!(total_liquidity_shares(&pos), 0);
    assert_eq!(
        validate_claimable(&pos, &[bin_arr]),
        Err(ValidationError::EmptyPosition)
    );
}

#[test]
fn maximum_slippage_constant_is_three() {
    assert_eq!(MAX_ACTIVE_BIN_SLIPPAGE, 3);
}

// ---------------------------------------------------------------------------
// `getLatestBlockhash` response decoding
// ---------------------------------------------------------------------------
//
// Regression: the no-nonce demo path used to trip `"blockhash not 32 bytes: 33"`
// because the code was decoding the base58 blockhash string as base64. The
// pinned value below is a real mainnet blockhash; it must round-trip to the
// same 32 bytes whether you decode it as base58 (correct) or base64 (the
// historical bug — note the lengths differ).
#[test]
fn get_latest_blockhash_response_decodes_as_base58() {
    use dlmm_core::rpc::decode_blockhash_from_response;

    // Real `getLatestBlockhash` response shape from mainnet-beta.
    let body = serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "result": {
            "context": { "slot": 348_000_000 },
            "value": {
                "blockhash": "9CmjKoWGqndHBRmRFL6jcc6cZs9cQttNkpTY4Y8d5vJ3",
                "lastValidBlockHeight": 348_000_016
            }
        }
    });

    let bytes = decode_blockhash_from_response(&body).expect("decode");
    assert_eq!(bytes.len(), 32);

    // Round-trip via base58 to lock the encoding: re-encoding the bytes must
    // produce the original string.
    assert_eq!(
        bs58::encode(bytes).into_string(),
        "9CmjKoWGqndHBRmRFL6jcc6cZs9cQttNkpTY4Y8d5vJ3"
    );

    // Sanity: the old base64 path produced 33 bytes — assert it here so the
    // mismatch is visible in the test output if anyone reintroduces the bug.
    let base64_len = base64::engine::general_purpose::STANDARD
        .decode("9CmjKoWGqndHBRmRFL6jcc6cZs9cQttNkpTY4Y8d5vJ3")
        .unwrap()
        .len();
    assert_eq!(base64_len, 33, "base58-as-base64 must NOT yield 32 bytes");
    assert_ne!(base64_len, bytes.len());
}

#[test]
fn get_latest_blockhash_response_rejects_malformed() {
    use dlmm_core::rpc::decode_blockhash_from_response;

    // Missing the value field.
    let v = serde_json::json!({ "jsonrpc": "2.0", "id": 1, "result": {} });
    assert!(decode_blockhash_from_response(&v).is_err());

    // Blockhash of the wrong length (31 bytes) — must error explicitly.
    let short = bs58::encode([0u8; 31]).into_string();
    let v = serde_json::json!({ "result": { "value": { "blockhash": short } } });
    match decode_blockhash_from_response(&v) {
        Err(msg) => assert!(msg.contains("not 32 bytes"), "got: {msg}"),
        Ok(_) => panic!("31-byte blockhash must be rejected"),
    }
}
